FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY test-servers/consistency_validator/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY test-servers/consistency_validator/consistency_validator.py .

CMD ["python", "consistency_validator.py"]